---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-nodeport-service-config-1
  labels:
    app: simple-nodeport-service
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss1"
    data-dir = "/var/lib/simple-nodeport-service/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-nodeport-service-1:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-nodeport-service-1:2379"
    initial-cluster = "ss1=http://simple-nodeport-service-1:2380,ss2=http://simple-nodeport-service-2:2380,ss3=http://simple-nodeport-service-3:2380"

  kubeconfig: |
    KUBECONFIG FILE HERE

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-nodeport-service-config-2
  labels:
    app: simple-nodeport-service
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss2"
    data-dir = "/var/lib/simple-nodeport-service/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-nodeport-service-2:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-nodeport-service-2:2379"
    initial-cluster = "ss1=http://simple-nodeport-service-1:2380,ss2=http://simple-nodeport-service-2:2380,ss3=http://simple-nodeport-service-3:2380"

  kubeconfig: |
    KUBECONFIG FILE HERE

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-nodeport-service-config-3
  labels:
    app: simple-nodeport-service
data:
  config.ini: |
    server-port = 8080

    [etcd]
    name = "ss3"
    data-dir = "/var/lib/simple-nodeport-service/"
    host-whitelist = "0.0.0.0"
    initial-advertise-peer-urls = "http://simple-nodeport-service-3:2380"
    listen-peer-urls = "http://0.0.0.0:2380"
    listen-client-urls = "http://0.0.0.0:2379"
    advertise-client-urls = "http://simple-nodeport-service-3:2379"
    initial-cluster = "ss1=http://simple-nodeport-service-1:2380,ss2=http://simple-nodeport-service-2:2380,ss3=http://simple-nodeport-service-3:2380"

  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
      KUBECONFIG FILE HERE
